letterpad/letterpad

.eslintrc.js
.github/ISSUE_TEMPLATE.md
README.md
api/middlewares.js
api/resolvers/author.js
api/schema/media.js
api/schema/post.js
api/schema/setting.js
api/schema/taxonomy.js
api/server.js
api/upload.js
api/utils/constants.js
api/utils/customStorage.js
api/utils/mail.js

Refactoring the api code base, majorly the server added notes in readme.

Cleaning api codebase

---

.babelrc
__tests__/__snapshots__/admin.createpost.test.js.snap
__tests__/admin.createpost.test.js
__tests__/admin.taxonomies.test.js
__tests__/empty-module.js
admin/components/Post/Categories.js
admin/components/Post/PostActions.js
admin/components/Post/PostPublish.js
admin/components/Post/Tags.js
admin/containers/Create/Create.js
package.json

Covering some tests for the admin dashboard:
- Testing Taxonomies
- Creating, deleting, adding tags
- Creating, deleting, adding categories
- Testing Post creation
- Testing Post publish

Tests for the admin dashbaord

---

README.md
utils/preinstall.sh
webpack/webpack.base.js

I was able to get `yarn install && theme=hugo yarn build` to pass on a new setup (Linux) after making the following changes:
* use https link for easier new developer setup
Helps avoid the following on first `yarn install`:
```
$ ./utils/preinstall.sh
Cloning into 'client/themes/hugo'...
The authenticity of host 'github.com (X.X.X.X)' can't be established.
RSA key fingerprint is SHA256:NOT_THE_REAL_SHA.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,X.X.X.X' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
error An unexpected error occurred: "Command failed.
Exit code: 128
Command: sh
Arguments: -c …
```

Installation

---

admin/components/Author/Social.js
shared/i18n/lang/en.json
shared/i18n/lang/fr.json
shared/i18n/lang/pl.json

Fixes for 3 issues: #35 , #36 , #37

Fix author's social information section

---

admin/components/Post/PostPublish.js

This PR addreses the issue https://github.com/letterpad/letterpad/issues/39

Fixed Post status

---

api/housekeeper/migrations/20180518224848-AddAuthorInfoField.js
api/housekeeper/migrations/20180519000052-AddDisqusField.js
api/housekeeper/migrations/20180519194323-addLogo.js
api/housekeeper/migrations/20180520140603-addSocialGithub.js
api/housekeeper/migrations/20180602095618-addGaField.js
api/housekeeper/migrations/20180622203056-addMediaInfoFields.js

Fix database migrations

---

admin/components/Post/Editors/RichText.js
admin/components/Post/FeaturedImage.js
admin/components/Settings/General.js
admin/containers/Media/Media.js
admin/util.js
api/middlewares.js
api/resolvers/author.js
api/server.js
api/utils/customStorage.js

- Insert multiple images during file upload for Posts and Pages (this will not work if you try to add exisitng images from media gallery).
- Featured image upload should be single.
- Uploading avatar and hero banner should be single.

Multi image upload

---

CONTRIBUTING.md

from
https://github.com/hashicorp/packer/blob/master/.github/CONTRIBUTING.md

docs: add a friendly contribution intro

---

__tests__/api.menu.test.js
api/seed/posts.js
api/seed/seed.js
package.json

* use async mkdirp
* parallelize posts insertion and few other parts of api seeding 
* use lesser awaits

refactor: parallelize parts of api.seed

---

admin/Routes.js
admin/app.js
admin/components/Post/Search.js
admin/containers/Secured.js

Removed console errors from admin

---

README.md

Multi-language support => Multi-language support with react-i18next
Add: You can play around with the Graphql API locally on [http://localhost:3030/graphql](http://localhost:3030/graphql)

[README] Docs update

---

admin/components/Settings/General.js
api/seed/seed.js
client/Routes.js
client/helpers/Paginate.js
client/helpers/Search.js
shared/apolloClient.js
shared/queries/Fragments.js

- Removed editor selection from admin
- Added created date and published date to posts while seeding
- Added pagination for tags and categories
- Fixed 501 redirection when token expires (only when basename is used)

Bugfixes and enhancements

---

admin/components/Navbar/MenuVertical.js
admin/components/Paginate.js
admin/public/pcss/admin/_navbar.pcss

Addresing https://github.com/letterpad/letterpad/issues/85

Fixed state of navbar

---

admin/components/Post/ArticleEdit.js
admin/components/Post/Editor.js
admin/components/Post/PostPublish.js

Addressing https://github.com/letterpad/letterpad/issues/89

Auto save posts with progress indicator

---

admin/features/themes/index.js
api/seed/.babelrc
api/seed/index.js
public/css/custom.css
webpack/webpack.dev.js
webpack/webpack.prod.js

Fix to https://github.com/letterpad/letterpad/issues/95

Save css from admin panel

---

admin/components/modal/index.js
admin/features/article/FeaturedImage.js
admin/features/article/topbar/PublishDropdown.js
admin/features/file-explorer/index.js

Currently the user can only set an image in the article as the featured image. 
This PR allows the user to set a custom featured image which may not be in the article.

[Feature] Custom featured image

---

admin/features/article/editor/slatejs/ToolBar.js

Prevent the buttons from being selected when clicking.

Disable user-select

---

api/server.js
package.json

This bug originated from https://github.com/letterpad/letterpad/pull/103. This PR fixes the graphql endpoint.

[Bug fix] Single port graphql url fix 

---

admin/features/header/index.js
admin/server.js
package.json

This bug originated from #103. This PR fixes the admin endpoint.

[Fix] Admin API url

---

api/resolvers/media.js

Fix issue with media items deleting

---

admin/features/article/Edit.js
admin/features/home/QuickDraft.js
admin/features/home/index.js
api/models/post.js
api/resolvers/post.js
shared/queries/Mutations.js

Fixes https://github.com/letterpad/letterpad/issues/121

Fix home draft creation

---

src/client/server/html.js

Fix the URL for google analytics to load from the correct domain

Fix spelling of google-analytics

---

src/graphql/context.ts
src/graphql/mail/mailqueue.ts
src/graphql/mail/new-post/content.ts
src/graphql/mail/templates/getTemplate.test.ts
src/graphql/queries/mutations.graphql
src/graphql/resolvers/post.mutation.ts
src/graphql/resolvers/setting.ts
src/graphql/resolvers/subscriber.ts
src/graphql/schema/subscribers.graphqls

Email tests

---

package.json
public/css/antd.css
public/css/antd.dark.css
public/css/editor.css
public/css/theme-variables.css
src/components/post-meta/index.tsx
src/components/post-meta/tags.tsx
src/components/post/components/title.tsx
src/components/tags/component.tsx
src/graphql/queries/queries.graphql
src/graphql/resolvers/tag.ts
src/graphql/schema/tags.graphqls
yarn.lock

Changed Css, tags, slug formatting.

Modified post meta

---

cypress/integration/publishPost.spec.ts
cypress/support/commands.ts
public/css/antd.css
public/css/antd.dark.css
public/css/globals.css
public/css/theme-variables.css
src/components/post-settings/index.tsx
src/components/post-settings/publishButton.tsx
src/components/post-settings/quickmenu.tsx
src/components/post-settings/tags.tsx
src/components/posts/header.tsx
src/graphql/resolvers/helpers.ts
src/graphql/resolvers/post.mutation.ts
src/pages/media.tsx
src/pages/migrate.tsx
src/pages/pages.tsx
src/pages/posts.tsx
src/pages/profile.tsx
src/pages/settings.tsx
src/pages/subscribers.tsx
src/pages/tags.tsx

Publishing of post was not very clear. This PR adds help text and improves publishing.
All changes are in settings of a post. The Republish button also has been moved inside settings.

Improve UX

---

src/components/feedback-form.tsx

Renaming the feedback button to report.

Rename feedback to report

---

src/components/feedback-form.tsx
src/components/file-explorer/index.tsx
src/components/file-explorer/providers/Internal.tsx
src/components/post/components/post.tsx
src/graphql/utils/imageAttributs.ts

This PR takes care of the below things:
- Renames the Feedback to Report.
- Fixes the modal frozen issue for media selection
- Fixes the Url issue when an image is deleted from the filesystem.

Improvements

---

public/css/editor.css
src/components/post/components/plugins/image/index.ts
src/components/profile/social.tsx

Added a delete icon which will show up when you click on image to select. This is easier to delete than using a backspace.
In addition, in Profile -> Social, I add `@` as prefix, so that users don't get confused.

Add delete icon in Post Image on clicking image

---

package.json
src/graphql/mail/domainMapSuccess/content.ts
src/graphql/mail/enqueueEmailAndSend.ts
src/graphql/resolvers/helpers.ts
src/graphql/services/domain/createOrUpdateDomain.ts
src/graphql/types.ts

While mapping domains, the response was incorrect due to an error which happens at DB level. This PR fixes that.

Fix response of  domain mapping

---

public/css/editor.css
src/components/file-explorer/index.tsx
src/components/post-settings/quickmenu.tsx
src/components/post/components/commands.ts
src/components/post/components/plugins/image/index.ts
src/components/post/components/post.tsx
src/components/post/components/tinymce/core.ts
src/components/post/components/tinymce/tinymce.tsx
src/components/post/context.tsx
src/graphql/resolvers/post.ts
src/graphql/schema/post.graphqls
src/graphql/services/post/getLetterpadLatestPost.ts
src/graphql/services/post/getLetterpadLatestPosts.ts
src/hooks/useLetterpadSession.ts

- Adds selection in image.
- Added LTR and RTL as an option in Editor for Arabic language.
- Added image upload progress icon in file explorer.
- Added ga user id with custom dimention name `userId`

Enhance image selection

---

src/components/theme-switcher.tsx
src/hooks/useLetterpadSession.ts

Also fix the initial event of theme change which gets auto executed if the theme is found in localstorage.

fix: custom dimension in ga

---

src/components/post/components/language-tool/grammar.ts
src/components/post/components/language-tool/utils.ts
src/components/post/components/tinymce/socket.ts
src/constants.ts
src/pages/api/socket.io.ts
src/types.ts

Language tool has moved to a new server. This URL is available in .env file

Change language tool url

---

.github/workflows/non-master-deploy.yml
apps/admin/cypress/support/commands.ts
apps/admin/src/components/builder/layout.tsx
apps/admin/src/components/builder/layouts/story-builder/masonry.tsx
apps/admin/src/components/builder/layouts/story-builder/wrapper.tsx
apps/admin/src/components/builder/toolbar/editSwitch.tsx
apps/admin/src/components/feedback-form.tsx
apps/admin/src/components/filters/index.tsx
apps/admin/src/components/metrics/MetricsCard.tsx
apps/admin/src/components/post-settings/deletePost.tsx
apps/admin/src/components/post-settings/index.tsx
apps/admin/src/components/post-settings/publishButton.tsx
apps/admin/src/components/post-settings/quickmenu.tsx
apps/admin/src/components/post/components/header.tsx
apps/admin/src/components/post/components/post.tsx
apps/admin/src/components/posts/header.tsx
apps/admin/src/components/sidebar/sidebar.tsx
apps/admin/src/components/theme-switcher.tsx
apps/admin/src/components/top-bar/topBar.tsx
apps/admin/src/components_v2/button/buttonv2.tsx
apps/admin/src/components_v2/select/select.tsx
apps/admin/src/graphql/types.ts
apps/admin/src/pages/creatives.tsx
apps/admin/src/pages/dashboard.tsx
apps/admin/src/pages/try-creatives.tsx
apps/client/layouts/creatives/photostory.tsx

Creatives live

---

apps/admin/src/components/metrics/MetricsCard.tsx
apps/admin/src/components/post/components/tinymce/socket.ts
apps/admin/src/components/post/components/tinymce/tinymce.tsx
apps/admin/src/pages/api/grammer.ts

Change grammar endpoint with environment variables

Change grammar endpoint

---

apps/admin/public/css/editor.css
apps/admin/src/components/file-explorer/index.tsx
apps/admin/src/components/file-explorer/providers/Unsplash.tsx
apps/admin/src/components/post-settings/index.tsx
apps/admin/src/components/post/components/commands.ts
apps/admin/src/components_v2/layouts/twoColumnLayout.tsx
apps/admin/src/pages/api/unsplash.ts
apps/admin/src/types.ts
apps/client/components/SEO.tsx
apps/client/css/tailwind.css

Currently we are using unsplash developer edition which allows only 50 api calls per hour. With production version we will have 5000 API calls.
Also fixed the image caption css.

Unsplash production ready

---

apps/admin/public/css/theme-variables.css
apps/admin/src/components/theme-switcher.tsx

Fixing a bug where Profile page was unable to scroll.

fix scroll issue

---

apps/admin/public/css/prism.css
apps/client/css/prism.css
apps/client/tailwind.config.js

Improve codeblock font size and colors in client.

Improve codeblocks

---

apps/client/components/Footer.tsx
apps/client/components/PageTitle.tsx
apps/client/components/SectionContainer.tsx
apps/client/components/Subscribe.tsx
apps/client/components/share/share.tsx
apps/client/css/creative.css
apps/client/css/prism.css
apps/client/css/tailwind.css
apps/client/layouts/PostLayout.tsx
apps/client/tailwind.config.js

Improve overall typography of client

Improve typography of client

---

apps/admin/src/graphql/db/seed/seed.ts
apps/client/components/LayoutWrapper.tsx
apps/client/components/Logo.tsx
apps/client/components/PostList.tsx
apps/client/components/SectionContainer.tsx
apps/client/css/tailwind.css
apps/client/layouts/AuthorLayout.tsx
apps/client/layouts/ListLayout.tsx
apps/client/layouts/PostLayout.tsx
apps/client/pages/index.tsx
apps/client/tailwind.config.js

Typography changes with fonts and spacing.

Font enhancement

---

apps/admin/public/css/editor.css
apps/admin/src/components/builder/layouts/story-builder/cell.tsx
apps/admin/src/components/builder/toolbar/mini-editor.tsx
apps/admin/src/components/post/components/tinymce/tinymce.tsx
apps/client/css/tailwind.css
apps/client/tailwind.config.js

Added a button in quick selection toolbar to highlight words/phrases.

Add word highlight

---

apps/admin/src/components_v2/accordion/accordion.tsx
apps/admin/src/components_v2/accordion/index.ts
apps/admin/src/components_v2/accordion/item.tsx
apps/admin/src/lib/onboard.ts
apps/admin/src/pages/settings.tsx
apps/client/layouts/ListLayout.tsx

chore: fix post list layout in client

---

apps/client/pages/feed.xml.tsx
apps/client/queries/queries.ts

Reverts letterpad/letterpad#452

Revert "feat: temp remove client feed"

---

apps/admin/src/components/settings/appearance.tsx
apps/admin/src/components/settings/integrations.tsx
apps/admin/src/graphql/db/seed/constants.js
apps/admin/src/graphql/db/seed/seed.ts
apps/admin/src/pages/settings.tsx
apps/client/components/LayoutWrapper.tsx
apps/client/components/PageTitle.tsx
apps/client/components/Subscribe.tsx
apps/client/components/Tag.tsx
apps/client/layouts/GridLayout.tsx
apps/client/layouts/ListLayout.tsx
packages/ui/css/tailwind.css

Tiny css enhancements for mobile.

Enhance mobile css with new design

---

apps/admin/cypress/e2e/publishPost.spec.ts
apps/admin/src/components/filters/index.tsx
apps/admin/src/components/post-settings/index.tsx
apps/admin/src/components/post-settings/publishButton.tsx
apps/admin/src/components/post-settings/warnings.tsx
apps/admin/src/components/sidebar/sidebar.tsx
apps/admin/src/components/tags/context.tsx
apps/admin/src/graphql/apolloBrowserClient.ts
apps/admin/src/graphql/schema/post.graphqls
apps/admin/src/graphql/services/stats.ts
apps/admin/src/pages/creatives.tsx
apps/admin/src/pages/posts.tsx
apps/client/pages/_app.tsx
packages/ui/index.tsx
packages/ui/src/components/input/input.tsx
packages/ui/src/components/modal/modal.tsx
packages/ui/src/components/popconfirm/popConfirm.tsx
packages/ui/src/components/select/select.tsx
packages/ui/src/hooks/useKeyPress.ts

@gorkemcetin has posted this issue https://github.com/letterpad/letterpad/issues/488 and has given a lot of good points on how to improve the experience of Letterpad. This PR takes care of a part of those issues which are mentioned below.
*UX/UI related*
* When I try to publish a page, it gives me a warning that it is not linked, and not visible. The style of this popup is not on par with the rest (modals).
* The author shouldn't be able to edit the /page section, e.g this word needs to be non-modifiable. 
* When I have a good number of posts, I would like to know how many posts are there, how many of them are draft and how many are published.
*Possible bugs*
* When I rename a tag, nothing happens (popup doesn't go away and there is no feedback). Probably a bug and I can report if that is …

Improvements and bugfixes

---

apps/admin/src/components/post/components/title.tsx
apps/admin/src/graphql/services/post/updatePost.ts
apps/admin/src/pages/posts.tsx

Focus on Input on creating a new page/post.

chore: focus on title when creating a new page

---

apps/admin/src/components/file-explorer/container.tsx
apps/admin/src/components/post-settings/index.tsx
apps/admin/src/components/post/components/dragdrop.tsx
apps/admin/src/components/post/components/post.tsx
apps/admin/src/components/post/components/tinymce/tinymce.tsx
apps/admin/src/components/post/components/title.tsx
apps/admin/src/components/post/components/wordCount.tsx
apps/admin/src/components/upload/preview.tsx
apps/admin/src/components/upload/upload.tsx
apps/admin/src/graphql/services/post/updatePost.ts
apps/admin/src/pages/posts.tsx
apps/admin/src/shared/utils.ts
packages/config/tailwind.config.js
packages/ui/css/editor.css

This PR adds drag drop support to all kind of image uploads.

Drag-drop-support

---

apps/admin/src/components/filters/index.tsx
apps/admin/src/components/main.tsx
apps/admin/src/components/posts/index.tsx
apps/admin/src/graphql/queries/queries.graphql
apps/admin/src/graphql/schema/post.graphqls
apps/admin/src/graphql/services/post/getPosts.ts
apps/admin/src/pages/creatives.tsx
apps/admin/src/pages/posts.tsx
packages/ui/src/components/table/header.tsx
packages/ui/src/components/table/rows.tsx
packages/ui/src/components/table/table.tsx
packages/ui/src/components/table/types.ts

Refer issue https://github.com/letterpad/letterpad/issues/496 for more information. This PR simplifies filtering posts/pages from admin dashboard.

Better filters UX in Admin Dashboard

---

.github/workflows/non-master-deploy.yml
LICENSE
apps/admin/LICENSE
apps/admin/src/components/layouts/LoginLayout.tsx
apps/admin/src/components/layouts/MessageLayout.tsx
apps/admin/src/components/layouts/site-footer.tsx
apps/admin/src/components/post/components/tinymce/config.ts
apps/admin/src/graphql/services/post/getPosts.ts
apps/admin/src/pages/themes.tsx
apps/client/pages/index.tsx

This PR addresses two of these issues:
https://github.com/letterpad/letterpad/issues/525 - When I remove all navigation, system shouldn't give server error
https://github.com/letterpad/letterpad/issues/524 - Update footer link

fix: navigation when empty

---

apps/admin/package.json
apps/admin/src/pages/api/auth/[...nextauth].ts
apps/admin/src/shared/getRootUrl.ts

Reverting back some changes. It was a cookie issue in browser.
The problem: While logging in, auth would throw an error saying invalid callback url.

Fix root url

---

apps/admin/package.json
apps/admin/src/pages/api/graphql.ts
apps/admin/tests/startServer.ts
apps/admin/tests/testSetup.ts
apps/client/.env
yarn.lock

Update Apollo Server

---

apps/admin/package.json
apps/client/src/app/about/page.tsx
apps/client/src/app/feed.xml/route.ts
apps/client/src/app/layout.tsx
apps/client/src/app/page.tsx
apps/client/src/app/page/[slug]/page.tsx
apps/client/src/app/post/[slug]/page.tsx
apps/client/src/app/preview/[hash]/page.tsx
apps/client/src/app/sitemap.xml/route.ts
apps/client/src/app/tag/[tag]/page.tsx
apps/client/src/app/tags/page.tsx
yarn.lock

chore: make client run on edge

---

apps/admin/src/app/(public)/login/_feature/views/login-form.tsx
apps/admin/src/shared/utils.ts

Redirect www.letterpad.app to letterpad.app.

fix: add www redirect

---

apps/admin/prisma/mysql/migrations/20240206124613_pageview_alter/migration.sql
apps/admin/prisma/mysql/schema_mysql.prisma
apps/admin/prisma/sqlite/migrations/20240206124627_pageview_alter/migration.sql
apps/admin/prisma/sqlite/schema.prisma
apps/admin/src/app/api/cron/1h/update-pageviews/route.ts
apps/admin/src/lib/redis.ts

Page views are not incrementing. This PR fixes that.

Fix: page view incremements

---

apps/admin/src/app/(public)/resources/[slug]/layout.tsx
apps/admin/src/app/(public)/resources/[slug]/page.tsx
apps/admin/src/app/(public)/resources/banner.tsx
apps/admin/src/app/(public)/resources/layout.tsx
apps/admin/src/app/(public)/resources/page.tsx
apps/admin/src/app/post/[postId]/_feature/components/post-settings/index.tsx
apps/admin/src/components/header/Header.tsx
apps/admin/src/resourceFetcher.ts

Adding some helpful guides to prepare user on how to use Letterpad.

Add helpful guides

---

apps/admin/src/graphql/db/seed/constants.js
apps/client/context/SessionProvider.tsx
apps/client/src/app/(others)/post/[slug]/post-footer.tsx
apps/client/src/app/layout.tsx
apps/client/src/app/page.tsx
apps/client/src/components/footer.tsx
apps/client/src/components/subscribePopup.tsx
apps/client/src/features/post/post.tsx
packages/ui/src/hooks/useIntersectionObserver.ts

As see in lot of other website, "Subscribe to my Blog" should appear after reading the blog. Made similar changes. Also changed the ugly footer. Now it looks somewhat decent.

Footer and subscription adjustments

---

apps/client/src/app/ClientThemeProvider.tsx
apps/client/src/app/layout.tsx
apps/client/src/app/page.tsx
apps/client/src/components/navbar/navbar.tsx
apps/client/themes/air/home_posts.tsx
apps/client/themes/getTheme.ts
packages/ui/src/components/theme/theme.helper.ts
turbo.json

1. Fix dark-light mode cookie preferences
2. Include PreHeader override for a theme - for NavBar.

fix: theme fixes; NavBar preheader components

---

apps/admin/src/app/settings/_feature/api.client.ts
apps/admin/src/app/settings/_feature/feature.tsx
apps/admin/src/lib/urqlClient.ts
packages/ui/src/components/popconfirm/popConfirm.tsx

Fixes https://github.com/letterpad/letterpad/issues/646

fix: account deletion

---

apps/admin/src/components/website_v2/index.tsx
apps/admin/src/graphql/resolvers/tag.ts
apps/admin/src/middleware.ts
apps/admin/src/resourceFetcher.ts
apps/client/src/app/(others)/layout.tsx
apps/client/src/app/layout.tsx
apps/client/src/middleware.ts

Added a setting to test maintainance mode in dev. The two configs available are `isInMaintenanceMode` and `isInMaintenanceModeDev`. They are set in edge configs

chore: maintainance mode in dev

---

apps/admin/next.config.js
apps/admin/src/app/post/[postId]/_feature/components/tinymce/config.ts
apps/client/next.config.js

Pasting any youtube URL in the editor will embed the video.

chore: allow youtube embed

---

apps/client/themes/wavique/home_posts.tsx
apps/client/themes/wavique/tag.tsx

Improve cards and its hover animations -

feat: improve cards for wavique theme

---

apps/admin/src/app/settings/_feature/components/appearance.tsx
apps/admin/src/app/settings/_feature/components/mixBlend.tsx
apps/admin/src/app/settings/_feature/feature.tsx
apps/admin/src/graphql/queries/partial.graphql
apps/admin/src/graphql/schema/settings.graphqls
packages/sdk/queries/settings.graphql
packages/sdk/src/graphql.ts

Adding a setting in Appearance to enable mix blend.

chore: allow users to select mixblend

---

apps/admin/src/app/(public)/pricing/checkout-btn.tsx
apps/admin/src/app/(public)/pricing/pricing-table.tsx
apps/admin/src/app/membership/checkout.ts
apps/admin/src/components/header/Header.tsx
apps/admin/src/resourceFetcher.ts
packages/ui/src/components/button/button.tsx
packages/ui/src/components/vercelEdgeConfig/server.ts

Fixing some cosmetic changes related to stripe payments.

chore: tiny payments fixes

---

apps/admin/src/app/settings/_feature/components/ai.tsx
apps/admin/src/app/settings/_feature/components/appearance.tsx
apps/admin/src/app/settings/_feature/components/integrations.tsx
apps/admin/src/app/settings/_feature/components/pages.tsx
apps/admin/src/app/settings/_feature/components/paypal.tsx
apps/admin/src/app/settings/_feature/components/seo.tsx
apps/admin/src/app/settings/_feature/feature.tsx
apps/admin/src/components/navigation-builder/index.tsx
apps/admin/src/components/navigation-builder/sortable/index.tsx
apps/admin/src/components/save-button/index.tsx
apps/admin/src/components/sidebar/menuItems.tsx
apps/admin/src/components/sidebar/sidebar.tsx

Fixes https://github.com/letterpad/letterpad/issues/676

chore: remove accordion from setting

---

apps/admin/src/app/domain-mapping/_feature/components/new-domain.tsx
apps/admin/src/app/post/[postId]/_feature/components/post-settings/index.tsx
apps/admin/src/app/post/[postId]/_feature/components/post-settings/preview.tsx
apps/admin/src/app/post/[postId]/_feature/components/post-settings/tags.tsx
apps/admin/src/app/post/[postId]/_feature/components/tinymce/config.ts
apps/admin/src/components/sidebar/sidebar.tsx
apps/admin/src/components/upgrade-plan-banner/upgrade-banner.tsx
apps/admin/src/hooks/useEscapeKey.ts
packages/ui/src/components/drawer/drawer.tsx
packages/ui/src/components/drawer/useEscapeKey.ts

fixes https://github.com/letterpad/letterpad/issues/683
fixes https://github.com/letterpad/letterpad/issues/682
fixes https://github.com/letterpad/letterpad/issues/677

chore: fix minor issues

---

apps/admin/src/app/domain-mapping/_feature/components/new-domain.tsx
apps/admin/src/app/posts/_feature/feature.tsx
apps/admin/src/app/profile/_feature/components/basic.tsx
apps/admin/src/app/profile/_feature/components/change-password.tsx
apps/admin/src/app/profile/_feature/components/change-username.tsx
apps/admin/src/app/profile/_feature/components/emailAndUsername.tsx
apps/admin/src/app/profile/_feature/components/social.tsx
apps/admin/src/app/profile/_feature/feature.tsx
apps/admin/src/app/settings/_feature/feature.tsx
apps/admin/src/components/sectionHeader/sectionHeader.tsx
apps/admin/src/components/sidebar/menuItems.tsx
apps/admin/src/components/sidebar/sidebar.tsx
apps/admin/src/components/upgrade-plan-banner/upgrade-banner.tsx
packages/ui/src/components/menu/index.ts
packages/ui/src/components/menu/menu.tsx

Removing accordions from profile.

chore: remove profile accordion

---

apps/client/src/components/title.tsx
apps/client/src/features/post/post.tsx

Making the cover image distinct by making it little bigger.

chore: improve cover image

---

apps/admin/src/app/creatives/_feature/feature.tsx
apps/admin/src/app/post/[postId]/_feature/AutoSaveForm.tsx
apps/admin/src/app/post/[postId]/_feature/api.client.ts
apps/admin/src/app/post/[postId]/_feature/feature.tsx
apps/admin/src/app/posts/_feature/feature.tsx
apps/admin/src/shared/utils.ts

Post settings can be saved from:
- /posts
- /post/post-id
- /creatives
Added a common module to save post settings for all three paths.

chore: save post settings

---

apps/admin/src/app/posts/_feature/feature.tsx
apps/admin/src/app/posts/_feature/filters/index.tsx
apps/admin/src/app/posts/_feature/header/index.tsx
apps/admin/src/components/file-explorer/container.tsx
apps/admin/src/components/file-explorer/providers/Gallery.tsx
packages/ui/css/editor.css
packages/ui/index.tsx
packages/ui/src/components/dropdown-menu/menuWithCheckbox.tsx
packages/ui/src/components/table2/index.tsx

chore: replace post filters with dropdown

---

apps/admin/src/components/file-explorer/providers/UploadZone.tsx
apps/admin/src/shared/utils.ts

Users should not care about the filesize. The software should handle this for the user.

chore: allow any size image

---

apps/admin/src/app/(public)/features/hero-text.tsx
apps/admin/src/app/layout.tsx
apps/admin/src/app/page/[postId]/page.tsx
apps/admin/src/app/post/[postId]/features.tsx
apps/admin/src/components/cookie-banner/action.tsx
apps/admin/src/components/cookie-banner/closeButton.tsx
apps/admin/src/components/cookie-banner/cookieBanner.tsx
apps/admin/src/components/website_v2/banner/action.tsx
apps/admin/src/components/website_v2/banner/aiAd.tsx
apps/admin/src/components/website_v2/index.tsx

Optimising the site. Remove homepage animation and reduced css which were blocking. Also removed font which was causing the LCP to go high.

Improve perf

---

apps/admin/src/components/header/Header.tsx
apps/admin/src/components/website_v2/announcement.tsx
apps/admin/src/components/website_v2/featured.tsx
apps/admin/src/components/website_v2/inView.tsx
apps/admin/src/components/website_v2/index.tsx
apps/admin/src/components/website_v2/topics.tsx
packages/ui/isomorphic.ts
packages/ui/src/components/skeleton/index.tsx

Improving performance using suspense and intersection observer. All server rendered.

Speedup homepage

---

apps/admin/src/app/layout.tsx
apps/admin/src/components/website_v2/announcement.tsx
apps/admin/src/components/website_v2/banner/aiAd.tsx
apps/admin/src/components/website_v2/banner/bannerAd.tsx
apps/admin/src/components/website_v2/click.tsx
apps/admin/src/components/website_v2/data.ts
apps/admin/src/components/website_v2/index.tsx
apps/admin/src/components/website_v2/layout.tsx
apps/admin/src/components/website_v2/renderCards.tsx
apps/admin/src/components/website_v2/topics.tsx
apps/admin/src/components/website_v2/trending.tsx
apps/admin/src/middleware.ts
packages/ui/src/components/tracking/index.ts

Having trending topics at the top before the main Hero banner may bring in more visibility to the platform. Trying out an AB Test

Ab test - Trending Topics
